import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { SidebarProvider } from "@/components/ui/sidebar";

import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "./(routes)/(root)/components";
import { Footer, NavBar } from "@/components/Shared";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${spaceGrotesk.variable} font-sans antialiased`}>
        <ClerkProvider>
          <SidebarProvider>
            <div className="flex min-h-screen w-full">
              <AppSidebar />

              <div className="flex flex-col flex-1 bg-stone-100">
                <NavBar />
                <main className="flex-1">{children}</main>
              </div>
             
            </div>
             
          </SidebarProvider>
          <div>
          <Footer />
          </div>
        </ClerkProvider>
      
      </body>
    </html>
  );
}