import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

import { Space_Grotesk } from "next/font/google";
import "./globals.css";
import { AppSidebar } from "./(routes)/(root)/components";
import { NavBar } from "@/components/Shared";

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={`${spaceGrotesk.variable} antialiased`}>
          <SidebarProvider>
            <AppSidebar/>

            <div className="w-full bg-stone-100 flex flex-col min-h-screen">
            <NavBar />

          
            <main className="flex-1 "> {children}</main>
              </div>
          </SidebarProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
